AWSTemplateFormatVersion: 2010-09-09

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: STD21006
  SSMBucket:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/test/ , /s3/bucket-name] ]
      Type: String
      Value: !GetAtt BucketS3.Arn