name: CD

on:
  push:
    branches:
      -  master

  pull_request:
    branches:
      - master

jobs:

  continuous-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Put branch_env into GITHUB_ENV
        run: echo "branch_env=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy s3 bucket
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.branch_env }}
          template: ././s3-compute.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides:
            "Env=${{ env.branch_env }}"
